<a href="https://colab.research.google.com/github/Huangphoux/standard-han-nom/blob/main/standard_han_nom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Prerequisites

In [ ]:
!git clone -q https://github.com/Huangphoux/standard-han-nom
%cd /content/standard-han-nom/
!pip install -q -r colab_requirements.txt
!pip install -q genanki

import pandas as pd
import numpy as np
import genanki

from google.colab import files

%mkdir results

fatal: destination path 'standard-han-nom' already exists and is not an empty directory.
/content/standard-han-nom
ERROR: Could not find a version that satisfies the requirement pywin32==308 (from versions: none)
ERROR: No matching distribution found for pywin32==308
mkdir: cannot create directory ‘results’: File exists

In [162]:
# Press here to remake to DataFrame
standard_table_lv1 = pd.DataFrame(pd.read_excel("character-lists/standard-han-nom-lv1.xlsx"))
standard_table_lv2 = pd.DataFrame(pd.read_excel("character-lists/standard-han-nom-lv2.xlsx"))

reform = pd.DataFrame(pd.read_csv('character-lists/reformed-chinese.tsv', sep='\t'))
website = pd.DataFrame(pd.read_html('character-lists/website.html')[0])

In [163]:
characters_by_grade = {}
new_characters_lv2 = {}
new_characters_by_grade = {}

characters_by_grade_flat = []
new_characters_by_grade_flat = []

for grade in range(1, 7): # there are grade 1,2,3,4,5,6
    with open('characters-by-grade/grade' + str(grade) + '.txt', 'r', encoding='utf8') as file:
        characters_by_grade[grade] = file.read().split()

    with open('new-characters-by-grade/grade' + str(grade) + '.txt', 'r', encoding='utf8') as file:
        new_characters_by_grade[grade] = file.read().split()

    for character in characters_by_grade[grade]:
        characters_by_grade_flat += character

    for character in new_characters_by_grade[grade]:
        new_characters_by_grade_flat += character

with open('new-characters-by-grade/level2.txt', 'r', encoding='utf8') as file:
        new_characters_lv2 = file.read().split()

In [164]:
# odd = [x for x in characters_by_grade_flat if x not in old_characters_by_grade_flat]
# print(odd)
# print(len(odd))

# print(len(old_characters_by_grade_flat))
# print(len(characters_by_grade_flat))

## 2. Data preprocessing

Although the source claimed there were 3975 characters in the tables, there appear to be only 3974. I plan to deal with this problem later.
Update: The reason is in the row 2192. The converter didn't read the character 洛 in this row (maybe because it's not fully display in the pdf file), so there was a missing character.

Despite doing a good job, the converter did not make a perfect table. There is a issue that is the column "Unnamed: 3", it should have been merged to the "Examples" column.

In [165]:
standard_table_lv1

,Character,Reading,Examples,Unnamed: 3,Note
0,阿,A,阿從 a tòng · 阿諛 a dua · 阿片 a phiến · 阿羅漢 ...,NaN,[翻] U+963F
1,妸,ả,淹妸,êm ả · 妸陶 ả đào,U+59B8
2,亞,Á,洲亞 Châu Á · 亞金 á kim · 亞聖 á thánh,NaN,U+4E9E
3,啊,à,勢啊？ Thế à? [嘆],NaN,U+554A
4,NaN,ã,嗢啊,ồn ã [𠸨],NaN
...,...,...,...,...,...
5104,𬺗,xuống,𬨠𬺗 lên xuống · 𨀈𬺗 bước xuống · 𬺗𩯀 xuống tóc,NaN,[異] 𫴋 𠖈 U+2CE97
5105,𦩰,xuồng,𣛥𦩰 be xuồng,NaN,U+26A70
5106,𩩫,xương,𩩫骨 xương cốt · 𤐚𩩫 hầm xương · 𩩫𦘹 xương sườn,NaN,[異] 昌 U+29A6B
5107,廠,XƯỞNG,工廠 công xưởng,NaN,U+5EE0
5108,倡,XƯỚNG,起倡 khởi xướng,NaN,U+5021

In [166]:
standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.cat(standard_table_lv1['Unnamed: 3'], sep = ' ', na_rep='')

standard_table_lv1.drop('Unnamed: 3', axis=1, inplace=True)

standard_table_lv1.loc[2190, 'Character'] = '洛'

From now on, I will deal with the missing values from the columns: Reading, Character and Unicode(create from Note column later).

In [167]:
# from above info, it seems like there is a missing value of Reading column
standard_table_lv1[standard_table_lv1['Reading'].isnull()]

     Character Reading    Examples    Note
2812         挪     NaN  挪威  Na Uy   U+632A

In [168]:
standard_table_lv2[standard_table_lv2['Reading'].isnull()]

     Character Reading     Examples     Note
1904         𥸁     NaN  𥸁𥯌  nan tre  U+25E01

In [169]:
# The reading is "Na" but was misunderstood to be NaN value. So I replace it.
standard_table_lv1.loc[2812, 'Reading'] = "NA"
standard_table_lv2.loc[1904, 'Reading'] = "nan"

In [170]:
standard_table_lv1 = pd.concat([standard_table_lv1, standard_table_lv2], ignore_index=True)

In [171]:
standard_table_lv1

,Character,Reading,Examples,Note
0,阿,A,阿從 a tòng · 阿諛 a dua · 阿片 a phiến · 阿羅漢 ...,[翻] U+963F
1,妸,ả,淹妸 êm ả · 妸陶 ả đào,U+59B8
2,亞,Á,洲亞 Châu Á · 亞金 á kim · 亞聖 á thánh,U+4E9E
3,啊,à,勢啊？ Thế à? [嘆],U+554A
4,NaN,ã,嗢啊 ồn ã [𠸨],NaN
...,...,...,...,...
8895,昌,XƯƠNG,昌盛 xương thịnh,U+660C
8896,唱,XƯỚNG,喝唱 hát xướng,U+5531
8897,NaN,xang,吋唱 xốn xang [𠸨] · 𫕸唱 xênh xang [𠸨],NaN
8898,䉅,xụp,㡴䉅 lụp xụp · 嚏䉅 xì xụp,U+4245
8899,㻠,xụt,嚏㻠 xì xụt,[翻] U+3EE0

In [172]:
# adding a Unicode column which is extracted from 'Note' column
# the Unicode columnn is the column of list (except there are some NaN values)
standard_table_lv1['Unicode'] = standard_table_lv1['Note'].str.findall(r'(U\+[0-9A-Fa-f]+)')
standard_table_lv1['Unicode'] = standard_table_lv1['Unicode'].apply(lambda x: np.nan if x == [] else x)

standard_table_lv1['Note'] = standard_table_lv1['Note'].str.replace(r'(U\+[0-9A-Fa-f]+)', "", regex=True)
standard_table_lv1['Note'] = standard_table_lv1['Note'].str.replace(' ?( ?) ?', "", regex=True)

standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.replace(r' ?(\[.*\]) ?', "", regex=True)
standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.strip()

#standard_table_lv1.drop('Note', axis=1, inplace=True)

In [173]:
# standard_table_lv1['Simplified'] = standard_table_lv1['Character'].str.findall(r'（(.*)）')
# standard_table_lv1['Simplified'] = standard_table_lv1.apply(
#     lambda row: row['Character'] if row['Simplified'] == [] else row['Simplified'],
#     axis=1
# )

standard_table_lv1['Character'] = standard_table_lv1['Character'].str.replace(r'（(.*)）', "", regex=True)
standard_table_lv1

,Character,Reading,Examples,Note,Unicode
0,阿,A,阿從 a tòng · 阿諛 a dua · 阿片 a phiến · 阿羅漢 ...,[翻],[U+963F]
1,妸,ả,淹妸 êm ả · 妸陶 ả đào,,[U+59B8]
2,亞,Á,洲亞 Châu Á · 亞金 á kim · 亞聖 á thánh,,[U+4E9E]
3,啊,à,勢啊？ Thế à?,,[U+554A]
4,NaN,ã,嗢啊 ồn ã,NaN,NaN
...,...,...,...,...,...
8895,昌,XƯƠNG,昌盛 xương thịnh,,[U+660C]
8896,唱,XƯỚNG,喝唱 hát xướng,,[U+5531]
8897,NaN,xang,吋唱 xốn xang,NaN,NaN
8898,䉅,xụp,㡴䉅 lụp xụp · 嚏䉅 xì xụp,,[U+4245]
8899,㻠,xụt,嚏㻠 xì xụt,[翻],[U+3EE0]

Now I will replace NaN values in 'Character' and 'Unicode' columns. Since every character is assigned with at least one code, and there are 3,975 characters and 3,975 lists, so that each character is associated with its own unique list.

Thus, we have this table (keep in mind one character might have n reading ways):

| Character                     | Reading   | Unicode                           |
|-------------------------------|-----------|-----------------------------------|
| character can be in this cell | reading_1 | the list (of code) can be in this |
| or this cell                  | reading_2 | or this                           |
| or this one                   | reading_n | or this                           |

I make an assumption that the list of code should be in the same row with reading_1.
The character is expected to be in that row too, but that's not always true. The next Code Cell proves that the character can only be in the row of reading_1 or the row of reading_2.

In [174]:
temp1 = standard_table_lv1['Character'].isna() & ~standard_table_lv1['Unicode'].isna()
special_index_list = []

for index, value in temp1.items():
    if value == True:
        special_index_list.append(index)
        special_index_list.append(index+1)
        special_index_list.append(index+2)

# standard_table_lv1.iloc[special_index_list]

In [175]:
# Now I bring all the character in its reading_2 row back to reading_1 row.
for index, value in temp1.items():
    if value == True:
        standard_table_lv1.loc[index, 'Character'] = standard_table_lv1.loc[index + 1, 'Character']
        standard_table_lv1.loc[index, 'Character'] = standard_table_lv1.loc[index + 2, 'Character']

        standard_table_lv1.loc[index + 1, 'Character'] = np.nan
        standard_table_lv1.loc[index + 2, 'Character'] = np.nan

In [176]:
# fill all NaN value in Character column and Unicode column
standard_table_lv1['Character'] = standard_table_lv1['Character'].ffill()
standard_table_lv1['Unicode'] = standard_table_lv1['Unicode'].ffill()
# standard_table_lv1['Simplified'] = standard_table_lv1['Simplified'].ffill()

# standard_table_lv1['Simplified'] = standard_table_lv1.apply(
#     lambda row: np.nan if row['Simplified'] == row['Character'] else row['Simplified'],
#     axis=1
# )
# standard_table_lv1['Simplified'] = standard_table_lv1['Simplified'].fillna('')

standard_table_lv1['Note'] = standard_table_lv1['Note'].fillna('')

Now we will assign each character to a grade from 1 to 5.

In [177]:
# first, I read all the characters from pdf to .txt file using below 3 lines of code to read pdf file
# then, I copied the result to .txt files manually

# from PyPDF2 import PdfReader
# reader = PdfReader("characters-by-grade.pdf")
# print(reader.pages[7].extract_text())

In [178]:
standard_table_lv1['grade'] = -1

for grade in range(1, 7):
    for character in characters_by_grade[grade]:
        row = standard_table_lv1.loc[standard_table_lv1['Character'].str.startswith(character, na=False)]
        standard_table_lv1.loc[row.index, 'grade'] = grade

# 7: nằm trong cấp 2
# 8: không nằm trong đâu cả

# for character in characters_lv2:
#     row = standard_table_lv1.loc[standard_table_lv1['Character'].str.startswith(character, na=False)]
#     standard_table_lv1.loc[row.index, 'grade'] = 7

standard_table_lv1['grade'] = standard_table_lv1['grade'].apply(lambda x: 7 if x == -1 else x)
# standard_table_lv1 = standard_table_lv1[standard_table_lv1['grade'].notna()]

In [179]:
# Cleaning all \n in Reading and Example
standard_table_lv1['Reading'] = standard_table_lv1['Reading'].str.replace('\n', '', regex=True)

standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.replace('\n', '', regex=True)
standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.replace(' ?· ?', '・', regex=True)
standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.replace(' ?・ ?', '\n', regex=True)
standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.replace('  ', ' ', regex=True)

standard_table_lv1['Note'] = standard_table_lv1['Note'].str.replace('\n', '', regex=True)
standard_table_lv1['Note'] = standard_table_lv1['Note'].str.replace('  ', ' ', regex=True)

standard_table_lv1['Note'] = standard_table_lv1['Note'].astype(str)

In [180]:
standard_table_lv1['Examples'] = standard_table_lv1['Examples'] + "\n" + standard_table_lv1['Note']
standard_table_lv1['Examples'] = standard_table_lv1['Examples'].str.strip("\n")

In [181]:
standard_table_lv1 = standard_table_lv1.drop(['Note', 'Unicode', 'grade'], axis=1)

In [182]:
# Export
# standard_table_lv1.to_excel('/content/after-processing-list.xlsx', index=False)

In [183]:
standard_table_lv1.to_csv('/content/after-processing-list.csv', index=False)
files.download("/content/after-processing-list.csv")

Now, we have a complete table need for creating anki decks.

## 3. Create anki decks

In [ ]:
# Create an Anki model (card layout)
han_nom_to_quoc_ngu_model = genanki.Model(
    1607392319,
    'Hán Nôm',
    fields=[
        {'name': 'Character'},
        {'name': 'Readings'},
        {'name': 'Audio'},
        {'name': 'Picture'},
        {'name': 'Examples'},
        {'name': 'Notes'},
        {'name': 'Grade'},
    ],
    templates=[
        {
            'name': 'Card 1',
            'qfmt': """<div style="font-size: 3em; font-family: minh">
{{Character}}
</div>""",
            'afmt': """{{FrontSide}}

<hr id=answer>

<div style="font-size: 2em; font-family: minh"">{{Readings}}</div>
<div>{{Audio}}</div>
<div>{{Picture}}</div>
<br>
<div class="examples">{{Examples}}</div>


{{#Notes}}
<br>
<div style="font-size: 0.5em; width: fit-content; max-width:50vw; margin: auto">
	<details>
  	<summary>Notes</summary>
		{{Notes}}
	</details>

</div>

{{/Notes}}
""",
        },
    ],
    css = """.card {
    font-family: gothic;
    font-size: 2em;
    text-align: center;
    color: black;
    background-color: #fdf6e3;
}

@font-face {
  font-family: gothic;
  src: url("_gothic.ttf");
}

@font-face {
  font-family: minh;
  src: url("_minh.ttf");
}""",
)

In [ ]:
# import random
# print(random.randrange(1 << 30, 1 << 31))

In [ ]:
one_giant_deck = genanki.Deck(2119493255, "Hán Nôm")

package = genanki.Package(one_giant_deck)
package.media_files = ['_gothic.ttf', '_minh.ttf']

def create_deck(new_df, deck_name, model, grade):
    match grade:
        case 7:
            subdeck_name = f'Cấp 2'
        case 8:
            subdeck_name = f'Ngoài bảng'
        case _:
            subdeck_name = f'Lớp {grade}'

    # subdeck = genanki.Deck(2059400110+grade+ord(deck_name[0]), f'{deck_name}::{subdeck_name}')  # Subdeck ID

    # package = genanki.Package(subdeck)
    # package.media_files = ['_gothic.ttf', '_minh.ttf']

    for _, row in new_df.iterrows():
        note = genanki.Note(
            model=model,
            fields=[str(row['Character']) if pd.notna(row['Character']) else '',
                    str(row['Readings']) if pd.notna(row['Readings']) else '',
                    '',
                    '',
                    str(row['Examples']) if pd.notna(row['Examples']) else '',
                    str(row['Note']) if pd.notna(row['Note']) else '',
                    str(row['grade']) if pd.notna(row['grade']) else '',]
        )
        # subdeck.add_note(note)
        one_giant_deck.add_note(note)

    # subdeck.write_to_file(f'results/{deck_name} - {subdeck_name}.apkg')

def create_HanNom_to_Quocngu_deck(df, deck_name, grade, model = han_nom_to_quoc_ngu_model):
    df_by_grade = df[df['grade'] == grade]

    new_df = pd.DataFrame(columns=['Character', 'Readings', 'Examples', 'Note', 'grade'])

    for _, row in df_by_grade.iterrows():
        character = str(row['Character']) if pd.notna(row['Character']) else ''
        reading = str(row['Reading']) if pd.notna(row['Reading']) else ''
        examples = str(row['Examples']) if pd.notna(row['Examples']) else ''
        note = str(row['Note']) if pd.notna(row['Note']) else ''
        grade_val = str(row['grade']) if pd.notna(row['grade']) else ''

        if character in new_df['Character'].values:
            new_df.loc[new_df['Character'] == character, 'Readings'] += ', ' + reading
            new_df.loc[new_df['Character'] == character, 'Examples'] += '<br>' + examples
        else:
            new_df.loc[len(new_df)] = [character, reading, examples, note, grade_val]

    temp = pd.DataFrame(columns=['Character', 'Readings', 'Examples', 'Note', 'grade'])

    # Handle cases for grades 1-6, 7 (level2), and 8 (outside the table)
    if grade in range(1, 7):
        for character in characters_by_grade[grade]:
             row = new_df[new_df['Character'].str.contains(character)]
             if not row.empty:
                temp.loc[len(temp)] = row.iloc[0].values
    # elif grade == 7:
    #      for character in characters_lv2:
    #          row = new_df[new_df['Character'].str.contains(character)]
    #          if not row.empty:
    #             temp.loc[len(temp)] = row.iloc[0].values
    # elif grade == 8:
    #     temp = new_df # For grade 8, keep all characters in new_df

    if grade != 7:
        new_df = temp

    create_deck(new_df, deck_name, model, grade)
    return new_df

sum = 0
for i in range(1, 8):
    new_df = create_HanNom_to_Quocngu_deck(standard_table_lv1, 'Hán Nôm', i)
    print(f"Grade {i} : {len(new_df.index)}")
    sum += len(new_df.index)

package.write_to_file('results/hannom.apkg')

print(sum)

Grade 1 : 244
Grade 2 : 342
Grade 3 : 464
Grade 4 : 478
Grade 5 : 490
Grade 6 : 1957
Grade 7 : 0
3975

In [ ]:
!zip -r /content/results.zip results

files.download("/content/results.zip")
# files.download("/content/after-processing-list.xlsx")

  adding: results/ (stored 0%)
  adding: results/hannom.apkg (deflated 41%)